### ISSUE TITLE
Add feature to regenerate indices from Admin interface

### ISSUE THREAD

**Issue by pastokes** [kcl-ddh/digipal#24]
It might be useful to allow Admin users to regenerate the search indices from the admin interface. I guess this is resource-intensive so shouldn't be allowed lightly, but for people running the system on Docker or sim. then asking them to go to the command line is a bit off-putting, and regenerating the indices on small projects I guess isn't that heavy. Perhaps have a local_settings to decide if it's available from the admin or not?

**Comment by geoffroy-noel-ddh** [comment]
This is a good point. 

A good solution would be to enable auto-indexing via a cronjob with a default value like twice a day. Another step would be to allow, as you suggest, to control that via the admin interface. So perhaps an editable settings variable with the time of day or number of times per day.

The second step would rely on cronjob and a Mezzanine admin settings. The later has not always worked as expected (according to Mezzanine documentation) in the past so it might have to wait until we upgrade Mezzanine to a newer version.

**Comment by pastokes** [comment]
The only problem with a chron job is that people would have to ensure that the VM is running at the right time of day. For small personal Docker setups I'm not sure this could be guaranteed, and it's also helpful to get quick feedback when entering data particularly at the start (for quality control, as reassurance that everything's working, etc.) What I initially had in mind was a button on the Admin interface to 'update indices now', but which could be disabled to prevent people unwittingly bogging down larger-scale projects.

**Comment by geoffroy-noel-ddh** [comment]
These are very good points, thank you. I agree with the need for an indexing button. I started thinking about it this week and this could be achieved with Celery, a task worker service for python. The development should be interesting because once we have this architecture in place with an admin area for task initiation and monitoring we can think of adding add background tasks to it (image import, conversion, refreshing derived fields, etc.).

You are also right about the risk of excessive manual re-indexing on the staging server. I've seen similar problems with other web applications in the past were demanding task were executed abusively. Providing more information about the last indexing time, the next scheduled time and allowing reindexing for each content type separately should help.

A very basic version would take 2-3 days to develop.

**Comment by pastokes** [comment]
Now implemented through re-indexer page (available through link in footer when logged in with admin access).
