### ISSUE TITLE
Add a subsection in the Admin Menu

### ISSUE THREAD

**Issue by HugoChevroton** [kcl-ddh/digipal#59]
Hi,

I'm trying to add a new table "Personne" to the database of digipal and then to create a specific section in the Admin Menu (part left of the http://127.0.0.1:8000/admin/ page) for access to this new table.
I'm actually working in a clone of the Digipal project and I native modify the file in the digipal folder.
Up to now, I added the following :

- In digipal/model.py :
class Personne(models.Model)
 	nom_personne = models.CharField(max_length=300)
 	...
 	
- In digipal/admin.py :
class PersonneAdmin(DigiPalModelAdmin):
    model = Personne
	...
	
admin.site.register(Personne, PersonneAdmin)

- In digipal/setting.py :
ADMIN_MENU_ORDER = (
 	...
    ('Personne', ('digipal.Personne')),
)

The migration is done. The server runs, but when I connect myself to the admin session, the new table Personne is in the Digipal subsection and not in a specific Personne subsection.
Did I miss something?

Note, if I do the following :
ADMIN_MENU_ORDER = (
 	...
    ('Personne', ('auth.User', 'digipal.Personne')),
)
With "auth.User" is a class existing previously in the project, the subsection Personne appears in the Admin Menu, and disappears when I come back to the line ('Personne', ('digipal.Personne')). 

Regard,
Hugo

**Comment by geoffroy-noel-ddh** [comment]
Hi @HugoChevroton I'll have a look at that soon although it seems to be a [Mezzanine feature](http://mezzanine.jupo.org/docs/configuration.html#admin-menu-order) rather than an Archetype problem. 

I just want to mention a few things in passing:

- I don't think you've created your repository by using github 'fork' function, have you? If you use the fork function your code history will be linked to that of main DigiPal code base. By doing so you can continue to download future changes in the parent repository. Without it your repository and DigiPal start to diverge completely and differences are hard to spot.
- I recommend to create new Django models in a separate file rather than editing the existing models.py & admin.py. Again this will make it easier for you to keep track & maintain your additions without risk of conflict with the core code base.
- I'm not sure what is the use of a Personne model in your project, but note that there is already a Person model in archetype. Mixing french and english names and having classes with such similar names may cause confusion / ambiguity.

**Comment by geoffroy-noel-ddh** [comment]
Also it might help if you create two branches in your repository: master (for the stable & tested code) and develop (for ongoing development). This way you can work mostly on the 'develop' branch, commit code that can be reviewed and tested by others even if it is not fully functional.

**Comment by pastokes** [comment]
I'm closing this given lack of activity and assuming it will be redundant once Archetype 3 is developed and released.
