### ISSUE TITLE
Best practice for having multiple Archetype containers?

### ISSUE THREAD

**Issue by ArcaLibraria** [kcl-ddh/digipal#65]
Dear Archetype team,

I currently have a fully vanilla installation of Archetype running on my computer (i.e. local only, running on macOS 11.4 Big Sur, via Docker and Kitematic using the instructions here: https://hub.docker.com/r/kingsdigitallab/archetype/).

I would like to make a second Archetype container for a second project, and I would like to know the best practice for doing this. The second container doesn't have to interact or communicate with the first in any way, I simply have a second separate corpus of manuscripts that I would like to analyse without contaminating my pre-existing Archetype installation.

Would the following changes to the docker command work, or should this be done in an entirely different way?

`docker stop archetype; docker pull kingsdigitallab/archetype:latest; docker run -d --name archetypedb2 -v  ~/Documents/Kitematic/archetype/home/digipal2/digipal_project2:/home/digipal2/digipal_project2:cached  -p 9081:80 kingsdigitallab/archetype:latest; echo "INSTALLED";`

I made the following changes to the standard mac/Linux docker installation instructions:
1. I removed the instruction to remove archetype `docker rm archetype;` (I have no idea if I needed to do this, I was scared leaving this in would remove my current container)
2. I renamed the container from `archetype` to `archetypedb2`
2. incremented the port by 1 from `9080:80` to `9081:80`
3. replaced `digipal` and `digipal_project` in the instructions to create volumes for the container with `digipal2` and `digipal_project2`. This was the bit I was the most uncertain about, i.e., where was the best place to "split" the file path for a second container.

Please forgive me if this is a really simple or really stupid question, this is the only thing I use Docker for and I am not a database specialist!

**Comment by pastokes** [comment]
Thanks for this question which certainly isn't silly. The lead developer of Archetype is currently on leave, and I'm by no means an expert in Docker so I can't advise on best practice, but here are my thoughts on what I *think* might work. I have never tried this, and again I'm not certain myself here, so if you have anything in your existing instance that you don't want to risk losing then please be sure to back it up first **and** be sure that you know how to restore it afterwards and have tested this, as there's a high risk of overwriting or corrupting your existing instance.

1. I think you're right not to `rm archetype`, and honestly I don't see any need to redo the `docker pull` either
2. Yes, renaming the container like this seems right to me
3. Changing the port like this makes sense to me too, to allow both containers to run at once. 
4. I'm pretty sure you should _not_ rename the digipal_project folder. Archetype looks here for project content and customisations, so I expect that renaming this folder will simply mean that Archetype will create a new `digipal_project`. My first try would be to leave the `digipal` folder also the same, but to change the path further up the chain, namely at `archetype` -> `archetypedb2` (I suggest archetypedb2 to match the name of the container for neatness rather than necessity). I also wouldn't change the path after the colon, either, as I believe that will change the path inside the container which I think should stay the same, so I'm pretty sure that will cause problems.

To be clear, then, the first thing that I would try is this:

`docker run -d --name archetypedb2 -v ~/Documents/Kitematic/archetypedb2/home/digipal/digipal_project:/home/digipal/digipal_project:cached -p 9081:80 kingsdigitallab/archetype:latest; echo "INSTALLED";`

I don't have a working Docker instance to hand right now to test, so again please be sure that you can restore your data before testing. Do let us know how you get on, too.

**Comment by ArcaLibraria** [comment]
Thank you so much for taking the time to reply and for offering so much help, particularly as the lead developer is currently on leave.

My short response is that I think(?) it worked, as I have a second instance of Archetype, and everything in both the old and new instances seems healthy and normal.

My longer response, including some slightly weird stuff in the Kitematic log, is below in case this is helpful to anyone else:

1. Before starting Docker and Kitematic I made a backup of my current Archetype container (hereafter archetype1), and then made sure I understood exactly how to restore from a backup in case something went wrong. I make backups every time I add new content, but I have (thankfully!) never needed to restore from a backup so I wanted to double-check I understood how to do that.
2. I started Docker and Kitematic and I made sure archetype1 said "stopped" and was **not** on/active/running in any way.
3. I opened up the the Docker CLI within Kitematic as that is the recommended step within the standard installation instructions and copied and pasted the script in @pastokes comment above and hit enter.
4.  The `INSTALLED` notification came back almost immediately, and when it did I typed `exit` into the terminal window and closed it.
5. The log screen in Kitematic began printing out a ton of stuff really fast, including `ALTER TABLE` tens of times and a bunch of stuff I had never seen before (pastebin of the log here: [https://pastebin.com/L68ZexUm]), and it felt like an extremely long 3 mins before the familiar `WEBSITE IS RUNNING` appeared. When `WEBSITE IS RUNNING` appeared I stopped the container, quit Kitematic, opened it again, and started up the new container. A much more normal initiation process appeared in the kitematic log window, `WEBSITE IS RUNNING` appeared around a minute later, and I was able to open the new instance of Archetype in my web browser and log into the site.
6. I closed the new instance of Archetype, and then opened my old one (archetype1) and verified that it loaded properly and hadn't been overwritten.

If everything seems to be working as intended then I'll start using my new instance of Archetype, but if anything seems amiss please let me know - I'm happy to keep testing.

**Comment by pastokes** [comment]
I'm happy to hear that it seems to have worked.

What you describe with the logs sounds normal to me. I haven't checked exactly, but the first time you run a new instance it usually runs a fairly long process to set up the database and indeed create the contents of the digipal_project folder. I would expect that this also happened with your first instance as well, but it may not have been evident if you weren't watching the log files.

In any case, do please test both instances properly, and then close the issue if you're happy that it worked.

**Comment by ArcaLibraria** [comment]
As far as I can tell everything is working as intended. Thank you so much for your help - Archetype has changed my life and I am so happy that I can now create additional containers for new self-contained projects.
